### ISSUE TITLE
Gemini 测试，不可以，不知道作者有没有测试过

### ISSUE THREAD

**Issue by wsdo** [Herm-Studio/StakeVladDracula#15]
<img width="844" alt="image" src="https://github.com/Herm-Studio/StakeVladDracula/assets/9738969/53bb640b-2de4-4cc0-be1e-a19048c037ec">

**Comment by WongLoki** [comment]
"message": "User location is not supported for the API use." 不是代码的问题，是你自己选择的部署地区Gemini不支持。
