### ISSUE TITLE
可以弄个Docker部署方法吗？

### ISSUE THREAD

**Issue by EmccK** [Herm-Studio/StakeVladDracula#16]
如题

**Comment by WongLoki** [comment]
可以，后续更新

**Comment by WongLoki** [comment]
Docker 已经创建好了，来试试吧～

[docker pull hermstudio/stakevladdracula-nginx:latest](https://hub.docker.com/r/hermstudio/stakevladdracula-nginx)

**Comment by WongLoki** [comment]
现在docker版本有一个问题，就是需要配置域名的ssl证书。 最好现在先用其他的方式使用，等我们后面的更新。
